FROM postgres:11.4-alpine

# For more information check https://hub.docker.com/_/postgres and
# https://docs.docker.com/samples/library/postgres/

USER postgres

# logs
# make sure it does not run as root
# create cathapi db user with correct permissions
#/var/lib/postgresql/data/postgresql.conf
