version: "3.5"

# Build all images:
#
# $ docker-compose -f Docker/docker-compose.yml build
#
# Start the development instance:
#
# $ docker-compose -f Docker/docker-compose.yml up
#
# Please note: Environment variables used by this Docker Compose setup are
#              spawned from a '.env' file. This file needs to be in the same
#              directory as the docker-compose command is run. Variables in this
#              file are defined by '<VARIABLE NAME>=<VALUE>'. Variables needed
#              are:
#                POSTGRES_PASSWORD - password for the superuser of Postgres, not
#                                    the password of the Django user accessing
#                                    the database
#                POSTGRES_DB - name of the database that will be created for
#                              the CATH-SM-API

volumes:
  db-store:
  www-static:
  www-logs:

services:
  cathapi-redis:
    restart: always
    build:
       context: ./redis/
    networks:
      default:
        aliases:
          - cathapi-redis

  cathapi-django:
    restart: always
    build:
      context: ../
      dockerfile: Docker/cathapi/Dockerfile
    depends_on:
      - cathapi-redis
      - postgres
    environment:
      - CATHAPI_DEBUG=CONTAINER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - www-static:/static
    command: /cathapi/entrypoint.sh gunicorn cathapi.wsgi -b 0.0.0.0:8080

  postgres:
    restart: always
    build:
      context: ./postgres/
      # Increase /dev/shm as hinted by the Docker Library page for Postgres
      # https://github.com/docker-library/docs/tree/master/postgres/
      # "shm_size" needs Docker-Compose v.3.5, before this file was 3.3.
      shm_size: '256MB'
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db-store:/var/lib/postgresql/data/

  nginx:
    restart: always
    build: 
      context: ./nginx/
    depends_on:
      - cathapi-django
    volumes:
      - www-static:/static
      - www-logs:/var/log/nginx
    ports:
      - "0.0.0.0:80:8000"

  cathapi-celery:
    restart: always
    build:
      context: ../
      dockerfile: Docker/cathapi/Dockerfile
    depends_on:
      - cathapi-redis
    environment:
      - CATHAPI_DEBUG=CONTAINER
      - I_AM_CELERY=1
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    command: celery -A cathapi worker

#  LocalWords:  env
